version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: task-manager-backend-dev
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=taskmanager
      - JWT_SECRET=yourSuperSecretKey123!@#
      - JWT_EXPIRES_IN=3600s
      - MONGO_URI=mongodb://mongodb:27017/taskmanager
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongodb-dev-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-dev-data:
  mongodb-dev-data: 